### ISSUE TITLE
Mejora removerSecuenciaDeEscape()

### ISSUE THREAD

**Issue by damorjuancruz** [kevporti/othelloGame#1]
# Mejora removerSecuenciaDeEscape()
Se podria utilizar replace() en vez de strip() para evitar saltos de linea indeseados en el medio de palabras.
Tambien se podria agregar que busque tabulaciones para evitar lo mismo.

**Comment by damorjuancruz** [comment]
@kevporti no entendi bien la idea de este

**Comment by kevporti** [comment]
@juancruzdamor Por ejemplo en los casos que el usuario haya escrito en el archivo algo como:
```
Ke        vin, N
Ju
an, B
```
Son casos extremos pero facilmente podrian ser errores de tipeo del usuario que quiza no se haya dado cuenta y haya apretado un tab (como en la primer linea) y un enter (como en la segunda linea) mientras escribia el archivo.
Utilizando .strip() solo cubre el caso de que los saltos por enter esten al final o inicio de un string, en cambio con replace se podria reemplazar esa secuencia de escape por un ''.

**Comment by damorjuancruz** [comment]
@kevporti eso ya seria un formato incorrecto del archivo, lo vamos a validar aunque no sea necesario (#2), pero para mi no deberiamos tampoco adaptarnos al formato incorrecto, simplemente detectarlo y avisar es suficiente. Ademas, por ejemplo, no tenemos forma de diferenciar si un salto de linea es intencional o no.
