### ISSUE TITLE
Mejoras a la Lectura de Archivo de Entrada

### ISSUE THREAD

**Issue by damorjuancruz** [kevporti/othelloGame#3]
# Mejoras a la Lectura de Archivo de Entrada
Cambiar el formato de apertura de archivo a uno que pregunte el nombre del archivo a utilizar, y que pida un tipo de archivo de formato .txt para evitar que el codigo sea manipulado.

Hay que plantearlo de una forma que, a modo de extra, mejore el testeo de multiples archivos. Las funciones que necesiten abrir el archivo podrian recibir su nombre como parametro, de esta forma se las pueden llamar con varios archivos distintos en los unit tests.

**Comment by damorjuancruz** [comment]
@kevporti  a que te referis con esto:

>(...),  y que pida un tipo de archivo de formato .txt para evitar que el codigo sea manipulado.

**Comment by kevporti** [comment]
Es para evitar que use otro formato de archivo que no sea '.txt', y que genere errores de los cuales no estamos enterados. Basicamente para cubrir los errores posibles predefinidos y crear uno custom, y junto con pedir el nombre del archivo, evitar que se tenga que cambiar manualmente la variable 'archivo' que tenemos definida ahora.

Los tests no deberian estar pensados para testear el archivo del usuario final sino del desarrollador (nosotros). Sirven para cubrir todos los casos posibles dentro de lo que la funcion deberia hacer, y si existe un caso en el cual falla, los tests de esa funcion estan mal o incompletos, pero eso es independientemente del archivo de entrada. Lo que yo tengo pensado es crear una carpeta con archivos de prueba con todos los casos posibles y utilizarlos para testear.

**Comment by kevporti** [comment]
Es para evitar que use otro formato de archivo que no sea '.txt', y que genere errores de los cuales no estamos enterados. Basicamente para cubrir los errores posibles predefinidos y crear uno custom, y junto con pedir el nombre del archivo, evitar que se tenga que cambiar manualmente la variable 'archivo' que tenemos definida ahora.

@juancruzdamor Los tests no deberian estar pensados para testear el archivo del usuario final sino del desarrollador (nosotros). Sirven para cubrir todos los casos posibles dentro de lo que la funcion deberia hacer, y si existe un caso en el cual falla, los tests de esa funcion estan mal o incompletos, pero eso es independientemente del archivo de entrada. Lo que yo tengo pensado es crear una carpeta con archivos de prueba con todos los casos posibles y utilizarlos para testear.

**Comment by damorjuancruz** [comment]
> Es para evitar que use otro formato de archivo que no sea '.txt', y que genere errores de los cuales no estamos enterados. Basicamente para cubrir los errores posibles predefinidos y crear uno custom, y junto con pedir el nombre del archivo, evitar que se tenga que cambiar manualmente la variable 'archivo' que tenemos definida ahora.

No afecta en nada la extension realmente. Pero si estoy de acuerdo en que hay que hacer que el nombre del archivo sea un input.

> Los tests no deberian estar pensados para testear el archivo del usuario final sino del desarrollador (nosotros). Sirven para cubrir todos los casos posibles dentro de lo que la funcion deberia hacer, y si existe un caso en el cual falla, los tests de esa funcion estan mal o incompletos, pero eso es independientemente del archivo de entrada. Lo que yo tengo pensado es crear una carpeta con archivos de prueba con todos los casos posibles y utilizarlos para testear.

A eso me referia, lo que quiero decir es que el hecho de que el nombre del archivo no este hardcodeado facilita el poder usar varios archivos (preparados especificamente para eso) dentro de los tests automatizados, por ejemplo:
```python
assert leerArchivo('test1.txt') == {}
assert leerArchivo('test2.txt') == {}
assert leerArchivo('test3.txt') == {}
```
lo cual ahora no seria posible ya que justamente esta hardcodeado.
