### ISSUE TITLE
Agregar en Main() caso de continuacion de partida

### ISSUE THREAD

**Issue by kevporti** [kevporti/othelloGame#9]
En el caso en que simularJuego no tire excepciones y se imprima el tablero, hay que verificar que se podían (o no) seguir haciendo jugadas (utilizando la función controlarSalteoDeJugada), y si no se podía, determinarGanador se ejecuta, sino, indicar de quien es el siguiente turno.

**Comment by damorjuancruz** [comment]
Me parece que esto lo voy a hacer en simularJuego para mantener toda la validacion ahi @kevporti

**Comment by kevporti** [comment]
@juancruzdamor Dale, yo puse el primer ejemplo que se me ocurrio pero eso que decis tiene mas sentido.
